# Generated by Django 3.2.6 on 2021-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_newpollingunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='newPollsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voters_reg_no', models.CharField(blank=True, max_length=200)),
                ('vote', models.CharField(choices=[('PDP', 'PDP'), ('DPP', 'DPP'), ('ACN', 'ACN'), ('PPA', 'PPA'), ('CDC', 'CDC'), ('JP', 'JP')], max_length=200)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='newPollingUnit',
        ),
    ]
